### PR TITLE
v5 support

### PR DESCRIPTION
**Pull request by christian-bromann**
## Problem

WebdriverIO is about to release a new major version that comes with a variety of breaking changes. This package wouldn't be compatible with it anymore.

## Solution

Modify `EyesWDIOUtils.js` to use new commands and change the way how results are handled.

## Comment

This is work in progress. There might be changes before release that might affect this PR. So please stay tuned.

Ref: https://github.com/webdriverio/v5/pull/79

### CODE REVIEW

**Comment by christian-bromann** [comment]
Is there anything missing here to move the changes forward?

**Comment by danielputerman** [comment]
@christian-bromann Thanks, sorry for the (extremely) delayed reply. Is this fix backwards compatible? 
(btw, we didn't merge it originally as you mentioned this was a WIP)

**Comment by christian-bromann** [comment]
Hey Daniel, no it is not so is v5 not backwards compatible with v4. I will work on getting this PR ready and will let you know.

**Comment by danielputerman** [comment]
@christian-bromann Thanks! We might create a separate v5 branch/repo then, to cont. support for wdio v4.

**Comment by paulopaquielli** [comment]
I had the same issue when I was upgrading WebdriverIo to v5, and this PR solves the problem of version upgrade! :slightly_smiling_face:
Hey @danielputerman do u need help to merge?
Hey @christian-bromann, I think u could help me. The library `"@wdio/eyes.webdriverio": "2.0.3"` has this error:

```
node_modules/@wdio/eyes.webdriverio/src/EyesWDIOUtils.js:377
SyntaxError: missing ) after argument list
```

Also, I couldn't find the repository where the lib was built.

**Comment by christian-bromann** [comment]
@paulopaquielli uff, yeah I remember I fixed this manually in the node_modules when I've seen it .. feel free to make a PR to https://github.com/christian-bromann/eyes.webdriverio.javascript/tree/cb-v5-support and I make another release in the @wdio namespace

**Comment by paulopaquielli** [comment]
@christian-bromann Thanks for the reply! I think you fixed this error in this commit https://github.com/christian-bromann/eyes.webdriverio.javascript/commit/db9d3e6bb5ca533ab01f4a3fd6f044f2d6fb0569 but it has not been published. I tested version 2.0.4, but the `src` folder is empty: /

**Comment by kevinmcdonnell** [comment]
@paulopaquielli did you get to the bottom of `src` missing?

What I've observed:

`npm install @wdio/applitools-service` results in `node_modules/@wdio/eyes.webdriverio` without a `src` dir

`npm install @applitools/eyes.webdriverio` results in `node_modules/@applitools/eyes.webdriverio` with `src` dir

I can't see any difference that may cause this, guess it could be an issue how the project was published?

**Comment by yuriieasternpeak** [comment]
@christian-bromann 
we've created new repo for wdio v5 support - https://github.com/applitools/eyes.webdriverio.javascript5

**Comment by christian-bromann** [comment]
@yuriieasternpeak awesome, what is the state of this, can I replace my fork with this one?

**Comment by yuriieasternpeak** [comment]
> @yuriieasternpeak awesome, what is the state of this, can I replace my fork with this one?

Now it's 5.1.0-beta.1. 
A lot of functionality from current version is implemented and tested, other functionality is implemented but not tested/fixed.
Now we are developing and supporting two repositories with wdio4 and wdio5 support.

**Comment by christian-bromann** [comment]
> Now we are developing and supporting two repositories with wdio4 and wdio5 support.

Sounds great! I will make sure to replace the libraries asap. Thank you!

**Comment by danielputerman** [comment]
@christian-bromann Thanks for all the help! We've used this PR as reference for the new repo.

**Pull request closed without merging**
